# Generated by Django 4.2.2 on 2023-06-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_protocolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='descricao',
        ),
    ]
