# Generated by Django 4.2.2 on 2023-06-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_servico_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='categoria_manutencao',
            field=models.ManyToManyField(null=True, to='servicos.categoriamanutenção'),
        ),
    ]
